/* ============================================================
   推免助手 PushMian Buddy — 种子数据（由 data.js 拆分，内容未改动）
   说明：仅在首次初始化时写入 localStorage，之后以本地存储为准。
   ============================================================ */

const SEED_VOCAB = [
{term:"好氧反硝化",en:"aerobic denitrification",def:"好氧条件下由特殊菌(如Halomonas)同步去除碳氮的过程，打破反硝化需严格厌氧的传统认知。",ex:"Aerobic denitrifiers can remove nitrate under oxic conditions.",syn:"有氧反硝化"},
{term:"反硝化",en:"denitrification",def:"微生物将NO3⁻经NO2⁻/NO/N2O最终还原为N2的过程，是脱氮终点。",ex:"Complete denitrification yields N2 rather than N2O.",syn:"脱氮"},
{term:"nirS",en:"nirS (nitrite reductase)",def:"编码亚硝酸盐还原酶(铜型)的基因，催化NO2⁻→NO，常用作反硝化功能标记。",ex:"nirS abundance reflects denitrifier activity.",syn:"亚硝酸盐还原酶基因"},
{term:"nosZ",en:"nosZ (N2O reductase)",def:"编码氧化亚氮还原酶的基因，催化N2O→N2，决定反硝化是否完整、是否逃逸温室气体。",ex:"nosZ-deficient strains emit N2O.",syn:"氧化亚氮还原酶基因"},
{term:"硝化",en:"nitrification",def:"好氧下NH4+经NH2OH→NO2⁻→NO3⁻的氧化过程，由氨氧化与亚硝酸氧化菌完成。",ex:"Nitrification consumes alkalinity.",syn:""},
{term:"厌氧氨氧化",en:"anammox",def:"厌氧下anammox菌将NH4+与NO2⁻直接转化为N2，节能省碳源。",ex:"Anammox reduces aeration by ~60%.",syn:"厌氧氨氧化"},
{term:"滨海湿地",en:"coastal wetland",def:"海陆交界的湿地生态系统，是蓝碳与氮去除热点，根际微域驱动好氧反硝化。",ex:"Coastal wetlands buffer nutrient loads.",syn:"海岸带湿地"},
{term:"蓝碳",en:"blue carbon",def:"红树林、海草床、盐沼等滨海生态系统固碳的能力，埋藏效率高。",ex:"Blue carbon mitigates climate change.",syn:""},
{term:"eDNA",en:"environmental DNA",def:"生物释放到环境(水/土)中的游离DNA，可用于物种监测而无需捕获。",ex:"eDNA detects invasive species early.",syn:"环境DNA"},
{term:"宏条形码",en:"metabarcoding",def:"对eDNA特定基因区段高通量测序以鉴定多物种的方法。",ex:"Metabarcoding reveals hidden diversity.",syn:""},
{term:"微塑料",en:"microplastics",def:"<5mm塑料颗粒，吸附污染物并可能携带抗性基因，形成'塑料圈'。",ex:"Microplastics host distinct biofilms.",syn:""},
{term:"浮游植物",en:"phytoplankton",def:"海洋初级生产者(硅藻/甲藻等)，贡献近半全球初级生产力。",ex:"Phytoplankton drive the biological pump.",syn:""},
{term:"浮游动物",en:"zooplankton",def:"随波逐流的动物(桡足类/磷虾等)，连接初级生产与高级消费者。",ex:"Copepods graze phytoplankton.",syn:""},
{term:"猛水蚤",en:"harpacticoid copepod",def:"底栖/附着的桡足类，摄食微藻与碎屑，是食物网关键一环。",ex:"Harpacticoids link detritus and fish.",syn:"猛水蚤类"},
{term:"上行/下行控制",en:"bottom-up / top-down control",def:"营养级间的调控方向：bottom-up由资源驱动，top-down由捕食者驱动。",ex:"Grazing exerts top-down control.",syn:""},
{term:"生物泵",en:"biological pump",def:"浮游植物固定碳并经食物网以颗粒有机碳沉降至深海的过程。",ex:"The biological pump stores carbon.",syn:""},
{term:"温跃层",en:"thermocline",def:"温度随深度急剧降低的水层，屏障垂向交换。",ex:"The thermocline blocks mixing.",syn:""},
{term:"密度跃层",en:"pycnocline",def:"密度随深度剧增的水层，抑制混合、常成缺氧区。",ex:"The pycnocline separates water masses.",syn:""},
{term:"赤潮",en:"harmful algal bloom (HAB)",def:"浮游生物暴发性增殖致海水变色，常由富营养化驱动。",ex:"HABs cause hypoxia and toxins.",syn:"有害藻华"},
{term:"海洋酸化",en:"ocean acidification",def:"海水吸收CO2致pH下降、CO3²⁻减少，威胁钙化生物。",ex:"Acidification harms calcifiers.",syn:""},
{term:"海洋碳汇",en:"ocean carbon sink",def:"海洋吸收储存CO2的能力，含物理泵/生物泵/蓝碳。",ex:"The ocean is a major carbon sink.",syn:""},
{term:"人工湿地",en:"constructed wetland",def:"基于生态过程设计的污水处理系统，整合植物/微生物/基质。",ex:"Constructed wetlands remove nitrogen.",syn:""},
{term:"活性氮",en:"reactive nitrogen",def:"除N2外具反应活性的氮形态(NO3⁻/NH4+等)，过量则污染。",ex:"Reactive nitrogen causes eutrophication.",syn:""},
{term:"富营养化",en:"eutrophication",def:"氮磷过量输入致藻华与缺氧的现象。",ex:"Eutrophication drives dead zones.",syn:""},
{term:"功能基因",en:"functional gene",def:"编码特定代谢功能(如反硝化)的基因，用以指示微生物过程。",ex:"Functional genes track N-cycling.",syn:""},
{term:"16S rRNA",en:"16S rRNA",def:"细菌核糖体RNA基因，用于物种分类与群落结构分析的标志。",ex:"16S rRNA reveals taxonomy.",syn:""},
{term:"qPCR",en:"quantitative PCR",def:"定量PCR，通过Ct值定量靶基因拷贝数，用于功能基因丰度。",ex:"qPCR quantified nirS copies.",syn:"实时荧光定量PCR"},
{term:"AAO工艺",en:"Anaerobic-Anoxic-Oxic",def:"厌氧-缺氧-好氧脱氮除磷主流市政工艺。",ex:"AAO removes N and P together.",syn:"A²O"},
{term:"MBR",en:"membrane bioreactor",def:"膜生物反应器，用膜分离替代二沉池，出水优占地小。",ex:"MBR yields high-quality effluent.",syn:"膜生物反应器"},
{term:"N2O",en:"nitrous oxide",def:"氧化亚氮，强温室气体，反硝化不完整时逃逸。",ex:"N2O has high warming potential.",syn:"氧化亚氮"},
{term:"团聚体/微域",en:"microzone / microenvironment",def:"根际等毫米级氧化还原异质区域，为好氧反硝化提供生境。",ex:"Roots create oxic-anoxic microzones.",syn:"微环境"},
{term:"硝酸盐还原酶",en:"narG / napA",def:"催化 NO3⁻→NO2⁻ 的酶基因，反硝化途径第一环。",ex:"narG abundance indicates nitrate reduction.",syn:"硝酸盐还原基因"},
{term:"亚硝酸盐还原酶(细胞色素型)",en:"nirK",def:"编码细胞色素 cd1-亚硝酸盐还原酶，与 nirS 为同功酶，常据此区分反硝化菌群。",ex:"nirK and nirS coexist in many strains.",syn:"亚硝酸盐还原酶基因"},
{term:"同步硝化反硝化",en:"simultaneous nitrification-denitrification (SND)",def:"好氧与缺氧过程在同一反应器/微域共现，实现同步脱氮。",ex:"SND saves tank volume and carbon.",syn:"SND"},
{term:"滤水率",en:"clearance rate",def:"单位时间个体滤过的海水体积，表征浮游动物摄食强度。",ex:"Clearance rate peaks at intermediate algae density.",syn:""},
{term:"摄食率",en:"ingestion rate",def:"单位时间个体摄食的食物量(常换算为碳)。",ex:"Ingestion rate was converted to carbon.",syn:""},
{term:"选择性指数",en:"selectivity index",def:"定量捕食者对 prey 偏好程度的指标(如 Ivlev 指数)。",ex:"Selectivity index revealed algae preference.",syn:""},
{term:"加标回收率",en:"spike recovery",def:"加入已知量标准品后测得的回收比例，评价 eDNA 提取效率的关键质控指标。",ex:"Spike recovery reached 85% after optimization.",syn:""},
{term:"微藻生物量",en:"microalgal biomass",def:"单位体积/面积微藻总量，常以叶绿素 a 或碳表示。",ex:"Microalgal biomass drives primary production.",syn:""}
];

/* —— 申请进度看板种子（示例，用户按需增删） —— */
const SEED_VOCAB_TB = [
  {
    "term": "海洋科学",
    "en": "Marine Science",
    "def": "海洋科学",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "物理海洋学",
    "en": "Physical Oceanography",
    "def": "物理海洋学",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海洋物理学",
    "en": "Marine Physics",
    "def": "海洋物理学",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海洋环流",
    "en": "Ocean Circulation",
    "def": "海洋环流",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "表层流",
    "en": "Surface Current",
    "def": "表层流",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "深层流",
    "en": "Deep Current",
    "def": "深层流",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "潮流",
    "en": "Tidal Current",
    "def": "潮流",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "潮汐",
    "en": "Tide",
    "def": "潮汐",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海啸",
    "en": "Tsunami",
    "def": "海啸",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "风暴潮",
    "en": "Storm Surge",
    "def": "风暴潮",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海浪",
    "en": "Ocean Wave",
    "def": "海浪",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "风浪",
    "en": "Wind Wave",
    "def": "风浪",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "涌浪",
    "en": "Swell",
    "def": "涌浪",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海洋温度",
    "en": "Ocean Temperature",
    "def": "海洋温度",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "盐度",
    "en": "Salinity",
    "def": "盐度",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "密度",
    "en": "Density",
    "def": "密度",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "压力",
    "en": "Pressure",
    "def": "压力",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "盐跃层",
    "en": "Halocline",
    "def": "盐跃层",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "密跃层",
    "en": "Pycnocline",
    "def": "密跃层",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "混合层",
    "en": "Mixed Layer",
    "def": "混合层",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海洋层结",
    "en": "Ocean Stratification",
    "def": "海洋层结",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "涡旋",
    "en": "Eddy",
    "def": "涡旋",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "上升流",
    "en": "Upwelling",
    "def": "上升流",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "下降流",
    "en": "Downwelling",
    "def": "下降流",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海洋化学",
    "en": "Marine Chemistry",
    "def": "海洋化学",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海洋生物地球化学",
    "en": "Marine Biogeochemistry",
    "def": "海洋生物地球化学",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "溶解氧",
    "en": "Dissolved Oxygen",
    "def": "溶解氧",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "营养盐",
    "en": "Nutrient",
    "def": "营养盐",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "硝酸盐",
    "en": "Nitrate",
    "def": "硝酸盐",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "磷酸盐",
    "en": "Phosphate",
    "def": "磷酸盐",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "硅酸盐",
    "en": "Silicate",
    "def": "硅酸盐",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "叶绿素 a",
    "en": "Chlorophyll a",
    "def": "叶绿素 a",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "溶解有机碳",
    "en": "Dissolved Organic Carbon",
    "def": "溶解有机碳",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "颗粒有机碳",
    "en": "Particulate Organic Carbon",
    "def": "颗粒有机碳",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "总有机碳",
    "en": "Total Organic Carbon",
    "def": "总有机碳",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "碳循环",
    "en": "Carbon Cycle",
    "def": "碳循环",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "氮循环",
    "en": "Nitrogen Cycle",
    "def": "氮循环",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "磷循环",
    "en": "Phosphorus Cycle",
    "def": "磷循环",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "硫循环",
    "en": "Sulfur Cycle",
    "def": "硫循环",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "痕量金属",
    "en": "Trace Metal",
    "def": "痕量金属",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "重金属",
    "en": "Heavy Metal",
    "def": "重金属",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "酸碱度",
    "en": "pH Value",
    "def": "酸碱度",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "碱度",
    "en": "Alkalinity",
    "def": "碱度",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "氧化还原电位",
    "en": "Redox Potential",
    "def": "氧化还原电位",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "生源要素",
    "en": "Biogenic Element",
    "def": "生源要素",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海洋污染",
    "en": "Marine Pollution",
    "def": "海洋污染",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "石油泄漏",
    "en": "Oil Spill",
    "def": "石油泄漏",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海洋生物学",
    "en": "Marine Biology",
    "def": "海洋生物学",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海洋生态学",
    "en": "Marine Ecology",
    "def": "海洋生态学",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海洋生态系统",
    "en": "Marine Ecosystem",
    "def": "海洋生态系统",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "游泳生物",
    "en": "Nekton",
    "def": "游泳生物",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "底栖生物",
    "en": "Benthos",
    "def": "底栖生物",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "珊瑚礁",
    "en": "Coral Reef",
    "def": "珊瑚礁",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海草床",
    "en": "Seagrass Bed",
    "def": "海草床",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "红树林",
    "en": "Mangrove",
    "def": "红树林",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海藻林",
    "en": "Kelp Forest",
    "def": "海藻林",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "河口",
    "en": "Estuary",
    "def": "河口",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "潮间带",
    "en": "Intertidal Zone",
    "def": "潮间带",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "大陆架",
    "en": "Continental Shelf",
    "def": "大陆架",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "水层区",
    "en": "Pelagic Zone",
    "def": "水层区",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "底栖区",
    "en": "Benthic Zone",
    "def": "底栖区",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海洋生物多样性",
    "en": "Marine Biodiversity",
    "def": "海洋生物多样性",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "物种多样性",
    "en": "Species Diversity",
    "def": "物种多样性",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "遗传多样性",
    "en": "Genetic Diversity",
    "def": "遗传多样性",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "生态系统多样性",
    "en": "Ecosystem Diversity",
    "def": "生态系统多样性",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "食物网",
    "en": "Food Web",
    "def": "食物网",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "营养级",
    "en": "Trophic Level",
    "def": "营养级",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "初级生产力",
    "en": "Primary Productivity",
    "def": "初级生产力",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "次级生产力",
    "en": "Secondary Productivity",
    "def": "次级生产力",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海洋生物地理学",
    "en": "Marine Biogeography",
    "def": "海洋生物地理学",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海洋地质学",
    "en": "Marine Geology",
    "def": "海洋地质学",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海洋地球物理学",
    "en": "Marine Geophysics",
    "def": "海洋地球物理学",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海底地形",
    "en": "Seafloor Topography",
    "def": "海底地形",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "大陆边缘",
    "en": "Continental Margin",
    "def": "大陆边缘",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "洋盆",
    "en": "Ocean Basin",
    "def": "洋盆",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "洋中脊",
    "en": "Mid-Ocean Ridge",
    "def": "洋中脊",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海沟",
    "en": "Trench",
    "def": "海沟",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海山",
    "en": "Seamount",
    "def": "海山",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "深海平原",
    "en": "Abyssal Plain",
    "def": "深海平原",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海洋沉积物",
    "en": "Marine Sediment",
    "def": "海洋沉积物",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "沉积物岩芯",
    "en": "Sediment Core",
    "def": "沉积物岩芯",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "岩石圈",
    "en": "Lithosphere",
    "def": "岩石圈",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "水圈",
    "en": "Hydrosphere",
    "def": "水圈",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "板块构造",
    "en": "Plate Tectonics",
    "def": "板块构造",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "地震活动",
    "en": "Seismic Activity",
    "def": "地震活动",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "火山作用",
    "en": "Volcanism",
    "def": "火山作用",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海洋矿产",
    "en": "Marine Mineral",
    "def": "海洋矿产",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "天然气水合物",
    "en": "Gas Hydrate",
    "def": "天然气水合物",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "油气",
    "en": "Oil and Gas",
    "def": "油气",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "古海洋学",
    "en": "Paleoceanography",
    "def": "古海洋学",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海平面变化",
    "en": "Sea-Level Change",
    "def": "海平面变化",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海洋地貌学",
    "en": "Marine Geomorphology",
    "def": "海洋地貌学",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "断层",
    "en": "Fault",
    "def": "断层",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "褶皱",
    "en": "Fold",
    "def": "褶皱",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "岩浆",
    "en": "Magma",
    "def": "岩浆",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海洋遥感",
    "en": "Marine Remote Sensing",
    "def": "海洋遥感",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "卫星遥感",
    "en": "Satellite Remote Sensing",
    "def": "卫星遥感",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "雷达遥感",
    "en": "Radar Remote Sensing",
    "def": "雷达遥感",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "光学遥感",
    "en": "Optical Remote Sensing",
    "def": "光学遥感",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "声学多普勒流速剖面仪",
    "en": "Acoustic Doppler Current Profiler",
    "def": "声学多普勒流速剖面仪",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "多波束测深仪",
    "en": "Multibeam Echo Sounder",
    "def": "多波束测深仪",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "单波束测深仪",
    "en": "Single-Beam Echo Sounder",
    "def": "单波束测深仪",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "侧扫声呐",
    "en": "Side-Scan Sonar",
    "def": "侧扫声呐",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "潜水器",
    "en": "Submersible",
    "def": "潜水器",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "遥控潜水器",
    "en": "Remotely Operated Vehicle",
    "def": "遥控潜水器",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "自主式水下航行器",
    "en": "Autonomous Underwater Vehicle",
    "def": "自主式水下航行器",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "温盐深剖面仪",
    "en": "CTD Profiler",
    "def": "温盐深剖面仪",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "水样采集器",
    "en": "Water Sampler",
    "def": "水样采集器",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "沉积物采样器",
    "en": "Sediment Sampler",
    "def": "沉积物采样器",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "浮游生物网",
    "en": "Plankton Net",
    "def": "浮游生物网",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海洋传感器",
    "en": "Marine Sensor",
    "def": "海洋传感器",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "数据浮标",
    "en": "Data Buoy",
    "def": "数据浮标",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海洋观测",
    "en": "Ocean Observation",
    "def": "海洋观测",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海洋数据同化",
    "en": "Marine Data Assimilation",
    "def": "海洋数据同化",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "地理信息系统",
    "en": "Geographic Information System",
    "def": "地理信息系统",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海洋环境科学",
    "en": "Marine Environmental Science",
    "def": "海洋环境科学",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海洋环境保护",
    "en": "Marine Environmental Protection",
    "def": "海洋环境保护",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海洋环境影响评价",
    "en": "Marine Environmental Impact Assessment",
    "def": "海洋环境影响评价",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海洋生态修复",
    "en": "Marine Ecological Restoration",
    "def": "海洋生态修复",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海洋保护区",
    "en": "Marine Protected Area",
    "def": "海洋保护区",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海洋资源",
    "en": "Marine Resource",
    "def": "海洋资源",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "渔业资源",
    "en": "Fishery Resource",
    "def": "渔业资源",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海洋可再生能源",
    "en": "Marine Renewable Energy",
    "def": "海洋可再生能源",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "潮汐能",
    "en": "Tidal Energy",
    "def": "潮汐能",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "波浪能",
    "en": "Wave Energy",
    "def": "波浪能",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海洋温差能",
    "en": "Ocean Thermal Energy Conversion",
    "def": "海洋温差能",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海洋生物技术",
    "en": "Marine Biotechnology",
    "def": "海洋生物技术",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海洋生物资源",
    "en": "Marine Bioresource",
    "def": "海洋生物资源",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海洋污染控制",
    "en": "Marine Pollution Control",
    "def": "海洋污染控制",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海洋垃圾",
    "en": "Marine Debris",
    "def": "海洋垃圾",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "有害藻华",
    "en": "Harmful Algal Bloom",
    "def": "有害藻华",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海洋保护",
    "en": "Marine Conservation",
    "def": "海洋保护",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海洋可持续发展",
    "en": "Sustainable Marine Development",
    "def": "海洋可持续发展",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海洋政策",
    "en": "Marine Policy",
    "def": "海洋政策",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海洋法",
    "en": "Marine Law",
    "def": "海洋法",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海洋空间规划",
    "en": "Marine Spatial Planning",
    "def": "海洋空间规划",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "气候变化",
    "en": "Climate Change",
    "def": "气候变化",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "全球变暖",
    "en": "Global Warming",
    "def": "全球变暖",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海冰",
    "en": "Sea Ice",
    "def": "海冰",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海洋脱氧",
    "en": "Ocean Deoxygenation",
    "def": "海洋脱氧",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海洋生态风险评估",
    "en": "Marine Ecological Risk Assessment",
    "def": "海洋生态风险评估",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海洋生物安全",
    "en": "Marine Biosecurity",
    "def": "海洋生物安全",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "海洋粮食安全",
    "en": "Marine Food Security",
    "def": "海洋粮食安全",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  }
]
;

const CHINESE_GLOSSARY = {
  "marine science": "海洋科学",
  "physical oceanography": "物理海洋学",
  "marine physics": "海洋物理学",
  "ocean circulation": "海洋环流",
  "surface current": "表层流",
  "deep current": "深层流",
  "tidal current": "潮流",
  "tide": "潮汐",
  "tsunami": "海啸",
  "storm surge": "风暴潮",
  "ocean wave": "海浪",
  "wind wave": "风浪",
  "swell": "涌浪",
  "ocean temperature": "海洋温度",
  "salinity": "盐度",
  "density": "密度",
  "pressure": "压力",
  "thermocline": "温跃层",
  "halocline": "盐跃层",
  "pycnocline": "密跃层",
  "mixed layer": "混合层",
  "ocean stratification": "海洋层结",
  "eddy": "涡旋",
  "upwelling": "上升流",
  "downwelling": "下降流",
  "marine chemistry": "海洋化学",
  "marine biogeochemistry": "海洋生物地球化学",
  "dissolved oxygen": "溶解氧",
  "nutrient": "营养盐",
  "nitrate": "硝酸盐",
  "phosphate": "磷酸盐",
  "silicate": "硅酸盐",
  "chlorophyll a": "叶绿素 a",
  "dissolved organic carbon": "溶解有机碳",
  "particulate organic carbon": "颗粒有机碳",
  "total organic carbon": "总有机碳",
  "carbon cycle": "碳循环",
  "nitrogen cycle": "氮循环",
  "phosphorus cycle": "磷循环",
  "sulfur cycle": "硫循环",
  "trace metal": "痕量金属",
  "heavy metal": "重金属",
  "ocean acidification": "海洋酸化",
  "ph value": "酸碱度",
  "alkalinity": "碱度",
  "redox potential": "氧化还原电位",
  "biogenic element": "生源要素",
  "marine pollution": "海洋污染",
  "oil spill": "石油泄漏",
  "microplastic": "微塑料",
  "marine biology": "海洋生物学",
  "marine ecology": "海洋生态学",
  "marine ecosystem": "海洋生态系统",
  "phytoplankton": "浮游植物",
  "zooplankton": "浮游动物",
  "nekton": "游泳生物",
  "benthos": "底栖生物",
  "coral reef": "珊瑚礁",
  "seagrass bed": "海草床",
  "mangrove": "红树林",
  "kelp forest": "海藻林",
  "estuary": "河口",
  "intertidal zone": "潮间带",
  "continental shelf": "大陆架",
  "pelagic zone": "水层区",
  "benthic zone": "底栖区",
  "marine biodiversity": "海洋生物多样性",
  "species diversity": "物种多样性",
  "genetic diversity": "遗传多样性",
  "ecosystem diversity": "生态系统多样性",
  "food web": "食物网",
  "trophic level": "营养级",
  "primary productivity": "初级生产力",
  "secondary productivity": "次级生产力",
  "marine biogeography": "海洋生物地理学",
  "marine geology": "海洋地质学",
  "marine geophysics": "海洋地球物理学",
  "seafloor topography": "海底地形",
  "continental margin": "大陆边缘",
  "ocean basin": "洋盆",
  "mid-ocean ridge": "洋中脊",
  "trench": "海沟",
  "seamount": "海山",
  "abyssal plain": "深海平原",
  "marine sediment": "海洋沉积物",
  "sediment core": "沉积物岩芯",
  "lithosphere": "岩石圈",
  "hydrosphere": "水圈",
  "plate tectonics": "板块构造",
  "seismic activity": "地震活动",
  "volcanism": "火山作用",
  "marine mineral": "海洋矿产",
  "gas hydrate": "天然气水合物",
  "oil and gas": "油气",
  "paleoceanography": "古海洋学",
  "sea-level change": "海平面变化",
  "marine geomorphology": "海洋地貌学",
  "fault": "断层",
  "fold": "褶皱",
  "magma": "岩浆",
  "marine remote sensing": "海洋遥感",
  "satellite remote sensing": "卫星遥感",
  "radar remote sensing": "雷达遥感",
  "optical remote sensing": "光学遥感",
  "acoustic doppler current profiler": "声学多普勒流速剖面仪",
  "multibeam echo sounder": "多波束测深仪",
  "single-beam echo sounder": "单波束测深仪",
  "side-scan sonar": "侧扫声呐",
  "submersible": "潜水器",
  "remotely operated vehicle": "遥控潜水器",
  "autonomous underwater vehicle": "自主式水下航行器",
  "ctd profiler": "温盐深剖面仪",
  "water sampler": "水样采集器",
  "sediment sampler": "沉积物采样器",
  "plankton net": "浮游生物网",
  "marine sensor": "海洋传感器",
  "data buoy": "数据浮标",
  "ocean observation": "海洋观测",
  "marine data assimilation": "海洋数据同化",
  "geographic information system": "地理信息系统",
  "marine environmental science": "海洋环境科学",
  "marine environmental protection": "海洋环境保护",
  "marine environmental impact assessment": "海洋环境影响评价",
  "marine ecological restoration": "海洋生态修复",
  "marine protected area": "海洋保护区",
  "marine resource": "海洋资源",
  "fishery resource": "渔业资源",
  "marine renewable energy": "海洋可再生能源",
  "tidal energy": "潮汐能",
  "wave energy": "波浪能",
  "ocean thermal energy conversion": "海洋温差能",
  "marine biotechnology": "海洋生物技术",
  "marine bioresource": "海洋生物资源",
  "marine pollution control": "海洋污染控制",
  "marine debris": "海洋垃圾",
  "eutrophication": "富营养化",
  "harmful algal bloom": "有害藻华",
  "marine conservation": "海洋保护",
  "sustainable marine development": "海洋可持续发展",
  "marine policy": "海洋政策",
  "marine law": "海洋法",
  "marine spatial planning": "海洋空间规划",
  "climate change": "气候变化",
  "global warming": "全球变暖",
  "sea ice": "海冰",
  "marine carbon sink": "海洋碳汇",
  "ocean deoxygenation": "海洋脱氧",
  "marine ecological risk assessment": "海洋生态风险评估",
  "marine biosecurity": "海洋生物安全",
  "marine food security": "海洋粮食安全",
  "the": "这/那（定冠词）",
  "and": "和/并且",
  "of": "……的",
  "to": "到/去/不定式",
  "in": "在……里",
  "is": "是",
  "are": "是（复数）",
  "for": "为了/对于",
  "with": "和/带有",
  "that": "那个/以致",
  "this": "这个",
  "can": "能/可以",
  "will": "将/会",
  "would": "将会/愿意",
  "should": "应该",
  "may": "可能/可以",
  "might": "也许",
  "must": "必须",
  "have": "有",
  "has": "有（三单）",
  "do": "做/助动词",
  "does": "做（三单）",
  "not": "不",
  "no": "不/没有",
  "yes": "是",
  "a": "一个",
  "an": "一个（元音前）",
  "we": "我们",
  "you": "你/你们",
  "they": "他们/它们",
  "he": "他",
  "she": "她",
  "it": "它",
  "our": "我们的",
  "your": "你的",
  "their": "他们的",
  "my": "我的",
  "me": "我（宾格）",
  "us": "我们（宾格）",
  "them": "他们（宾格）",
  "what": "什么",
  "how": "如何/怎样",
  "why": "为什么",
  "when": "何时",
  "where": "哪里",
  "who": "谁",
  "which": "哪一个",
  "but": "但是",
  "or": "或者",
  "so": "所以",
  "if": "如果",
  "because": "因为",
  "while": "然而/当……时",
  "as": "作为/因为/当",
  "at": "在",
  "by": "被/通过",
  "from": "从",
  "on": "在……上",
  "out": "向外",
  "up": "向上",
  "down": "向下",
  "about": "关于",
  "into": "进入",
  "over": "在……上方/超过",
  "under": "在……下",
  "after": "在……之后",
  "before": "在……之前",
  "during": "在……期间",
  "through": "通过/穿过",
  "such": "这样的",
  "also": "也",
  "more": "更多",
  "most": "最/大多数",
  "less": "更少",
  "many": "许多",
  "some": "一些",
  "all": "全部",
  "each": "每个",
  "both": "两者都",
  "between": "在……之间",
  "among": "在……之中",
  "within": "在……之内",
  "without": "没有",
  "against": "反对/靠着",
  "across": "横过",
  "toward": "朝向",
  "due": "由于/到期的",
  "based": "基于……的",
  "related": "相关的",
  "compared": "相比",
  "however": "然而",
  "therefore": "因此",
  "thus": "于是",
  "moreover": "此外",
  "first": "第一",
  "second": "第二",
  "finally": "最后",
  "important": "重要的",
  "significant": "显著的",
  "essential": "必要的",
  "vital": "至关重要的",
  "key": "关键的",
  "major": "主要的",
  "various": "各种各样的",
  "different": "不同的",
  "several": "几个",
  "these": "这些",
  "those": "那些",
  "than": "比",
  "etc": "等等",
  "research": "研究",
  "science": "科学",
  "marine": "海洋的",
  "ocean": "海洋",
  "oceanic": "海洋的",
  "coastal": "海岸的",
  "sea": "海",
  "seas": "海（复数）",
  "seawater": "海水",
  "ecosystems": "生态系统",
  "ecosystem": "生态系统",
  "organisms": "生物/有机体",
  "organism": "生物体",
  "species": "物种",
  "biodiversity": "生物多样性",
  "ecological": "生态的",
  "ecology": "生态学",
  "environmental": "环境的",
  "environment": "环境",
  "climate": "气候",
  "global": "全球的",
  "carbon": "碳",
  "energy": "能量",
  "data": "数据",
  "analysis": "分析",
  "study": "研究",
  "development": "发展",
  "protection": "保护",
  "sustainable": "可持续的",
  "productivity": "生产力",
  "temperature": "温度",
  "acidification": "酸化",
  "photosynthesis": "光合作用",
  "biology": "生物学",
  "biological": "生物学的",
  "physical": "物理的",
  "chemical": "化学的",
  "geological": "地质的",
  "chemistry": "化学",
  "physics": "物理学",
  "coral": "珊瑚",
  "habitats": "栖息地",
  "habitat": "栖息地",
  "zones": "带/区",
  "zone": "区带",
  "resources": "资源",
  "interest": "兴趣",
  "rich": "丰富的",
  "introduce": "介绍",
  "academic": "学术的",
  "fieldwork": "野外工作",
  "sea-going": "出海的",
  "remote": "远程的",
  "sensing": "传感",
  "impacts": "影响",
  "impact": "冲击/影响",
  "supporting": "支持",
  "support": "支持",
  "provide": "提供",
  "ability": "能力",
  "activities": "活动",
  "activity": "活动",
  "human": "人类的",
  "water": "水",
  "food": "食物",
  "change": "改变",
  "changing": "变化中的",
  "including": "包括",
  "main": "主要的",
  "high": "高的",
  "low": "低的",
  "large": "大的",
  "small": "小的",
  "deep-sea": "深海的",
  "deep": "深的",
  "shallow": "浅的",
  "surface": "表面",
  "underlying": "潜在的/底层的",
  "primary": "初级的/主要的",
  "secondary": "次级的生产者",
  "producer": "生产者",
  "consumer": "消费者",
  "predator": "捕食者",
  "prey": "猎物",
  "population": "种群",
  "community": "群落",
  "nutrients": "营养盐",
  "oxygen": "氧气",
  "dissolved": "溶解的",
  "sediment": "沉积物",
  "sediments": "沉积物",
  "microbial": "微生物的",
  "microbe": "微生物",
  "bacteria": "细菌",
  "bacterial": "细菌的",
  "gene": "基因",
  "genes": "基因",
  "genetic": "基因的",
  "protein": "蛋白质",
  "enzyme": "酶",
  "cell": "细胞",
  "tissue": "组织",
  "plankton": "浮游生物",
  "algae": "藻类",
  "algal": "藻类的",
  "fish": "鱼",
  "fisheries": "渔业",
  "mammal": "哺乳动物",
  "bird": "鸟",
  "invertebrate": "无脊椎动物",
  "pollution": "污染",
  "contamination": "污染",
  "contaminant": "污染物",
  "plastic": "塑料",
  "metal": "金属",
  "heavy": "重的",
  "toxic": "有毒的",
  "toxin": "毒素",
  "warming": "变暖",
  "deoxygenation": "脱氧",
  "stratification": "层结",
  "current": "当前的",
  "currents": "洋流",
  "circulation": "环流",
  "tidal": "潮汐的",
  "wave": "波浪",
  "wind": "风",
  "storm": "风暴",
  "surge": "涌浪/增水",
  "mixing": "混合",
  "mix": "混合",
  "layer": "层",
  "mixed": "混合的",
  "stratified": "分层的",
  "basin": "洋盆",
  "basins": "洋盆",
  "transport": "输送",
  "transporting": "输送",
  "transported": "被输送",
  "regulate": "调节",
  "regulation": "法规",
  "regulating": "调节的",
  "regulator": "调节者",
  "govern": "支配",
  "control": "控制",
  "drive": "驱动",
  "driven": "被驱动的",
  "response": "响应",
  "respond": "响应",
  "adapt": "适应",
  "adaptation": "适应",
  "adaptive": "适应的",
  "survive": "生存",
  "survival": "生存",
  "extreme": "极端的",
  "environments": "环境",
  "fluctuating": "波动的",
  "stress": "胁迫",
  "stressful": "有压力的",
  "tolerance": "耐受性",
  "resistant": "抗性的",
  "sensitive": "敏感的",
  "vulnerable": "脆弱的",
  "resilient": "有韧性的",
  "resilience": "恢复力",
  "stable": "稳定的",
  "stability": "稳定性",
  "dynamic": "动态的",
  "dynamics": "动态",
  "variability": "变率",
  "fluctuation": "波动",
  "oscillation": "振荡",
  "cycle": "循环",
  "cycling": "循环",
  "seasonal": "季节性的",
  "annual": "年度的",
  "diurnal": "昼夜的",
  "spatial": "空间的",
  "temporal": "时间的",
  "regional": "区域的",
  "local": "当地的",
  "latitudinal": "纬度的",
  "longitudinal": "经度的",
  "vertical": "垂直的",
  "horizontal": "水平的",
  "abundance": "丰度",
  "diversity": "多样性",
  "richness": "丰富度",
  "evenness": "均匀度",
  "frequency": "频率",
  "intensity": "强度",
  "duration": "持续时间",
  "magnitude": "量级",
  "extent": "程度/范围",
  "degree": "程度",
  "rate": "速率",
  "scale": "尺度",
  "range": "范围",
  "trend": "趋势",
  "pattern": "模式",
  "structure": "结构",
  "function": "功能",
  "role": "角色/作用",
  "effect": "效应",
  "mechanism": "机制",
  "feature": "特征",
  "characteristic": "特征",
  "property": "属性",
  "parameter": "参数",
  "variable": "变量",
  "factor": "因素",
  "condition": "条件",
  "process": "过程",
  "processes": "过程",
  "method": "方法",
  "methods": "方法",
  "model": "模型",
  "theory": "理论",
  "concept": "概念",
  "principle": "原理",
  "system": "系统",
  "result": "结果",
  "results": "结果",
  "show": "显示",
  "shows": "显示",
  "shown": "被显示",
  "indicate": "表明",
  "indicates": "表明",
  "demonstrate": "证明",
  "suggest": "建议",
  "reveal": "揭示",
  "revealed": "被揭示",
  "find": "发现",
  "finding": "发现",
  "findings": "研究发现",
  "observe": "观察",
  "observed": "被观察",
  "measure": "测量",
  "measured": "被测",
  "monitor": "监测",
  "monitoring": "监测",
  "assess": "评估",
  "assessment": "评估",
  "evaluate": "评价",
  "evaluation": "评价",
  "develop": "发展",
  "developed": "发达的",
  "developing": "发展中的",
  "improve": "改善",
  "improved": "被改善",
  "improvement": "改进",
  "enhance": "增强",
  "enhanced": "增强的",
  "reduce": "减少",
  "reduced": "减少的",
  "reduction": "减少",
  "remove": "去除",
  "removal": "去除",
  "recover": "恢复",
  "recovery": "恢复",
  "recovered": "被回收",
  "optimize": "优化",
  "optimization": "优化",
  "optimized": "优化后的",
  "yield": "产量",
  "purity": "纯度",
  "quality": "质量",
  "quantity": "数量",
  "concentration": "浓度",
  "level": "水平/层次",
  "increase": "增加",
  "increased": "增加的",
  "decrease": "减少",
  "decreasing": "减少的",
  "accumulate": "积累",
  "accumulation": "积累",
  "release": "释放",
  "emit": "排放",
  "emission": "排放",
  "generate": "产生",
  "generation": "产生",
  "produce": "生产",
  "produced": "被生产",
  "create": "创造",
  "form": "形成",
  "flow": "流动",
  "flux": "通量",
  "exchange": "交换",
  "transfer": "转移",
  "transform": "转化",
  "transformation": "转化",
  "conversion": "转换",
  "reaction": "反应",
  "interaction": "相互作用",
  "feedback": "反馈",
  "evolution": "演化",
  "growth": "生长",
  "reproduction": "繁殖",
  "mortality": "死亡率",
  "migration": "迁移",
  "dispersion": "扩散",
  "colonization": "定殖",
  "succession": "演替",
  "understanding": "理解",
  "explore": "探索",
  "exploration": "探索",
  "investigate": "调查",
  "investigation": "调查",
  "examine": "检查",
  "identify": "识别",
  "identified": "被识别",
  "determine": "确定",
  "describe": "描述",
  "description": "描述",
  "explain": "解释",
  "explanation": "解释",
  "discuss": "讨论",
  "consider": "考虑",
  "consideration": "考虑",
  "require": "需要",
  "requirement": "要求",
  "involve": "涉及",
  "involved": "涉及的",
  "enable": "使能够",
  "allow": "允许",
  "help": "帮助",
  "use": "使用",
  "used": "被使用的",
  "using": "使用",
  "apply": "应用",
  "application": "应用",
  "present": "呈现",
  "represent": "代表",
  "potential": "潜在的/潜力",
  "future": "未来的",
  "recent": "最近的",
  "ancient": "古老的",
  "early": "早期的",
  "late": "晚期的",
  "long": "长的",
  "short": "短的",
  "new": "新的",
  "old": "旧的",
  "natural": "自然的",
  "artificial": "人工的",
  "complex": "复杂的",
  "simple": "简单的",
  "common": "常见的",
  "unique": "独特的",
  "similar": "相似的",
  "opposite": "相反的",
  "particular": "特定的",
  "specific": "具体的",
  "general": "一般的",
  "typical": "典型的",
  "normal": "正常的",
  "abnormal": "异常的",
  "regular": "规律的",
  "irregular": "不规则的",
  "constant": "恒定的",
  "active": "活跃的",
  "passive": "被动的",
  "positive": "正向的",
  "negative": "负向的",
  "neutral": "中性的",
  "better": "更好的",
  "worse": "更差的",
  "best": "最好的",
  "worst": "最差的",
  "big": "大的",
  "tiny": "微小的",
  "huge": "巨大的",
  "massive": "大量的",
  "great": "伟大的",
  "little": "少的",
  "few": "少的",
  "much": "许多",
  "enough": "足够的",
  "sufficient": "充足的",
  "insufficient": "不足的",
  "full": "满的",
  "empty": "空的",
  "complete": "完整的",
  "incomplete": "不完整的",
  "partial": "部分的",
  "total": "总计的",
  "whole": "整个的",
  "half": "一半的",
  "single": "单个的",
  "double": "双倍的",
  "multiple": "多个的",
  "diverse": "多样的",
  "same": "相同的",
  "other": "其他的",
  "another": "另一个",
  "either": "两者之一",
  "neither": "两者都不",
  "whether": "是否",
  "although": "尽管",
  "though": "虽然",
  "since": "自从/因为",
  "until": "直到",
  "unless": "除非",
  "once": "一旦",
  "nor": "也不",
  "yet": "然而",
  "around": "围绕",
  "along": "沿着",
  "near": "靠近",
  "far": "远的",
  "close": "近的",
  "distant": "遥远的",
  "national": "国家的",
  "international": "国际的",
  "universal": "普遍的",
  "special": "特殊的",
  "rare": "稀有的",
  "unusual": "不寻常的",
  "unstable": "不稳定的",
  "static": "静态的",
  "good": "好的",
  "bad": "坏的",
  "hypothesis": "假说",
  "experiment": "实验",
  "experimental": "实验的",
  "observation": "观测",
  "survey": "调查",
  "interview": "访谈",
  "questionnaire": "问卷",
  "simulation": "模拟",
  "modeling": "建模",
  "prediction": "预测",
  "forecast": "预报",
  "estimation": "估算",
  "calculation": "计算",
  "review": "综述",
  "summary": "摘要",
  "introduction": "引言",
  "conclusion": "结论",
  "discussion": "讨论",
  "reference": "参考文献",
  "citation": "引用",
  "author": "作者",
  "reader": "读者",
  "student": "学生",
  "teacher": "教师",
  "professor": "教授",
  "researcher": "研究者",
  "scientist": "科学家",
  "expert": "专家",
  "engineer": "工程师",
  "manager": "管理者",
  "leader": "领导者",
  "team": "团队",
  "society": "社会",
  "organization": "组织",
  "institution": "机构",
  "government": "政府",
  "policy": "政策",
  "law": "法律",
  "standard": "标准",
  "rule": "规则",
  "guideline": "指南",
  "plan": "计划",
  "strategy": "策略",
  "program": "项目/计划",
  "action": "行动",
  "operation": "操作",
  "responsibility": "责任",
  "right": "权利",
  "obligation": "义务",
  "benefit": "益处",
  "cost": "成本",
  "price": "价格",
  "value": "价值",
  "money": "金钱",
  "fund": "资金",
  "resource": "资源",
  "budget": "预算",
  "investment": "投资",
  "economy": "经济",
  "market": "市场",
  "trade": "贸易",
  "industry": "工业",
  "business": "商业",
  "company": "公司",
  "product": "产品",
  "service": "服务",
  "technology": "技术",
  "innovation": "创新",
  "progress": "进步",
  "success": "成功",
  "failure": "失败",
  "crisis": "危机",
  "solution": "溶液",
  "answer": "答案",
  "issue": "问题",
  "topic": "主题",
  "subject": "主题",
  "theme": "主题",
  "domain": "领域",
  "scope": "范围",
  "limit": "限制",
  "edge": "边缘",
  "center": "中心",
  "core": "核心",
  "base": "基础",
  "foundation": "基础",
  "top": "顶部",
  "bottom": "底部",
  "side": "侧面",
  "front": "前面",
  "back": "后面",
  "inside": "内部",
  "outside": "外部",
  "place": "地方",
  "location": "位置",
  "position": "位置",
  "direction": "方向",
  "path": "路径",
  "route": "路线",
  "distance": "距离",
  "speed": "速度",
  "velocity": "速度",
  "force": "力",
  "work": "工作",
  "heat": "热",
  "light": "光",
  "sound": "声音",
  "radiation": "辐射",
  "signal": "信号",
  "noise": "噪声",
  "color": "颜色",
  "ph": "酸碱度",
  "nitrogen": "氮",
  "phosphorus": "磷",
  "sulfur": "硫",
  "salt": "盐",
  "ion": "离子",
  "electron": "电子",
  "molecule": "分子",
  "atom": "原子",
  "particle": "颗粒",
  "fluid": "流体",
  "gas": "气体",
  "liquid": "液体",
  "solid": "固体",
  "rock": "岩石",
  "soil": "土壤",
  "sand": "沙",
  "mud": "泥",
  "ice": "冰",
  "snow": "雪",
  "rain": "雨",
  "volume": "体积",
  "mass": "质量",
  "sample": "样品",
  "compound": "化合物",
  "substance": "物质",
  "material": "材料",
  "information": "信息",
  "knowledge": "知识",
  "evidence": "证据",
  "example": "例子",
  "case": "案例",
  "problem": "问题",
  "challenge": "挑战",
  "opportunity": "机会",
  "threat": "威胁",
  "damage": "损害",
  "loss": "损失",
  "health": "健康",
  "safety": "安全",
  "security": "安全",
  "efficiency": "效率",
  "performance": "表现",
  "capacity": "能力",
  "advantage": "优势",
  "disadvantage": "劣势",
  "difference": "差异",
  "similarity": "相似性",
  "relationship": "关系",
  "connection": "联系",
  "balance": "平衡",
  "network": "网络",
  "chain": "链",
  "web": "网",
  "gradient": "梯度",
  "boundary": "边界",
  "interface": "界面",
  "depth": "深度",
  "altitude": "海拔",
  "latitude": "纬度",
  "longitude": "经度",
  "state": "状态",
  "status": "状态",
  "phase": "阶段",
  "stage": "阶段",
  "step": "步骤",
  "period": "时期",
  "time": "时间",
  "date": "日期",
  "year": "年",
  "season": "季节",
  "day": "天",
  "hour": "小时",
  "minute": "分钟",
  "document": "文档",
  "report": "报告",
  "paper": "论文",
  "article": "文章",
  "book": "书",
  "journal": "期刊",
  "conference": "会议",
  "meeting": "会议",
  "course": "课程",
  "lecture": "讲座",
  "seminar": "研讨会",
  "training": "培训",
  "education": "教育",
  "learning": "学习",
  "teaching": "教学",
  "project": "项目",
  "question": "问题",
  "affect": "影响",
  "affected": "受影响的",
  "affecting": "影响中的",
  "influence": "影响",
  "cause": "导致",
  "caused": "被导致的",
  "lead": "导致",
  "leading": "主导的",
  "resulting": "由此产生的",
  "play": "扮演",
  "plays": "起……作用",
  "playing": "起……作用",
  "contribute": "贡献",
  "contributing": "贡献的",
  "maintain": "维持",
  "maintaining": "维持的",
  "sustain": "维持",
  "sustaining": "维持的",
  "sustained": "持续的",
  "promote": "促进",
  "promoting": "促进的",
  "facilitate": "促进",
  "prevent": "防止",
  "preventing": "防止的",
  "protect": "保护",
  "protecting": "保护的",
  "conserve": "保护/保育",
  "restore": "恢复",
  "restoring": "恢复的",
  "understand": "理解",
  "analyze": "分析",
  "analyzing": "分析中的",
  "distribute": "分布",
  "circulate": "循环",
  "grow": "生长",
  "shift": "转移",
  "vary": "变化",
  "differ": "不同",
  "manage": "管理",
  "accelerate": "加速；促进",
  "accelerates": "加速；促进",
  "accelerated": "加速的；被加速的",
  "accelerating": "加速中",
  "activate": "激活；活化",
  "activates": "激活",
  "activated": "被激活的",
  "activating": "激活",
  "adhere": "黏附；附着",
  "adheres": "黏附",
  "adhered": "附着",
  "adhering": "附着",
  "adsorb": "吸附",
  "adsorbs": "吸附",
  "adsorbed": "被吸附的",
  "adsorbing": "吸附中",
  "aggregate": "聚集；聚合",
  "aggregates": "聚集",
  "aggregated": "聚集的",
  "aggregating": "聚集",
  "amplify": "放大；扩增",
  "amplifies": "扩增",
  "amplified": "被放大的",
  "amplifying": "放大",
  "bind": "结合",
  "binds": "结合",
  "bound": "结合的",
  "binding": "结合",
  "bloom": "大量繁殖；藻华",
  "blooms": "大量繁殖",
  "bloomed": "繁殖的",
  "blooming": "繁殖中",
  "burrow": "掘穴；穴居",
  "burrows": "穴居",
  "burrowed": "穴居的",
  "burrowing": "穴居",
  "colonize": "定殖；拓殖",
  "colonizes": "定殖",
  "colonized": "被定殖的",
  "colonizing": "定殖",
  "compete": "竞争",
  "competes": "竞争",
  "competed": "竞争",
  "competing": "竞争",
  "decompose": "分解",
  "decomposes": "分解",
  "decomposed": "被分解的",
  "decomposing": "分解中",
  "degrade": "降解",
  "degrades": "降解",
  "degraded": "降解的",
  "degrading": "降解",
  "deposit": "沉积；沉淀",
  "deposits": "沉积",
  "deposited": "沉积的",
  "depositing": "沉积",
  "disperse": "分散；扩散",
  "disperses": "分散",
  "dispersed": "分散的",
  "dispersing": "分散",
  "distributes": "分布",
  "distributed": "被分布的",
  "distributing": "分布",
  "dominate": "主导",
  "dominates": "主导",
  "dominated": "被主导的",
  "dominating": "主导",
  "emerge": "出现；浮现",
  "emerges": "出现",
  "emerged": "出现的",
  "emerging": "出现的",
  "encounter": "遇到；遭遇",
  "encounters": "遇到",
  "encountered": "遇到的",
  "encountering": "遇到",
  "excrete": "排泄",
  "excretes": "排泄",
  "excreted": "被排泄的",
  "excreting": "排泄",
  "exploit": "开发；利用",
  "exploits": "开发",
  "exploited": "被开发的",
  "exploiting": "开发",
  "flourish": "繁盛；茂盛",
  "flourishes": "繁盛",
  "flourished": "繁盛的",
  "flourishing": "繁盛",
  "fluctuate": "波动；起伏",
  "fluctuates": "波动",
  "fluctuated": "波动的",
  "fragment": "碎片；碎裂",
  "fragments": "碎片",
  "fragmented": "碎片化的",
  "fragmenting": "碎裂",
  "graze": "啃食；放牧",
  "grazes": "啃食",
  "grazed": "被啃食的",
  "grazing": "啃食",
  "hatch": "孵化",
  "hatches": "孵化",
  "hatched": "孵化的",
  "hatching": "孵化中",
  "hover": "盘旋",
  "hovers": "盘旋",
  "hovered": "盘旋的",
  "hovering": "盘旋",
  "inhabit": "栖息；居住于",
  "inhabits": "栖息",
  "inhabited": "有生物栖息的",
  "inhabiting": "栖息",
  "inhibit": "抑制",
  "inhibits": "抑制",
  "inhibited": "被抑制的",
  "inhibiting": "抑制",
  "intercept": "拦截；截获",
  "intercepts": "拦截",
  "intercepted": "被拦截的",
  "intercepting": "拦截",
  "invade": "入侵；侵入",
  "invades": "入侵",
  "invaded": "被入侵的",
  "invading": "入侵",
  "isolate": "分离；隔离",
  "isolates": "分离",
  "isolated": "分离的；孤立的",
  "isolating": "分离",
  "locate": "定位",
  "locates": "定位",
  "located": "位于",
  "locating": "定位",
  "mate": "交配；配对",
  "mates": "交配",
  "mated": "交配的",
  "mating": "交配",
  "mediate": "介导；中介",
  "mediates": "介导",
  "mediated": "被介导的",
  "mediating": "介导",
  "molt": "蜕皮；换羽",
  "molts": "蜕皮",
  "molted": "蜕皮的",
  "molting": "蜕皮",
  "occupy": "占据；占领",
  "occupies": "占据",
  "occupied": "被占据的",
  "occupying": "占据",
  "overlap": "重叠；叠加",
  "overlaps": "重叠",
  "overlapped": "重叠的",
  "overlapping": "重叠",
  "penetrate": "渗透；穿透",
  "penetrates": "穿透",
  "penetrated": "穿透的",
  "penetrating": "穿透",
  "persist": "持续；存留",
  "persists": "持续",
  "persisted": "持续的",
  "persisting": "持续",
  "radiate": "辐射；放射",
  "radiates": "辐射",
  "radiated": "辐射的",
  "radiating": "辐射",
  "recede": "消退；后退",
  "recedes": "后退",
  "receded": "后退的",
  "receding": "后退",
  "recruit": "补充；招募",
  "recruits": "补充",
  "recruited": "被招募的",
  "recruiting": "招募",
  "regenerate": "再生",
  "regenerates": "再生",
  "regenerated": "再生的",
  "regenerating": "再生",
  "retreat": "后退；退缩",
  "retreats": "后退",
  "retreated": "后退的",
  "retreating": "后退",
  "scavenge": "食腐；觅食腐肉",
  "scavenges": "食腐",
  "scavenged": "食腐的",
  "scavenging": "食腐",
  "secrete": "分泌",
  "secretes": "分泌",
  "secreted": "被分泌的",
  "secreting": "分泌",
  "settle": "沉降；定居",
  "settles": "沉降",
  "settled": "沉降的；定居的",
  "settling": "沉降",
  "spawn": "产卵",
  "spawns": "产卵",
  "spawned": "产卵的",
  "spawning": "产卵",
  "starve": "饿死；挨饿",
  "starves": "饿死",
  "starved": "饥饿的",
  "starving": "饥饿中",
  "submerge": "沉没；淹没",
  "submerges": "沉没",
  "submerged": "沉没的",
  "submerging": "沉没",
  "subside": "沉降；消退",
  "subsides": "沉降",
  "subsided": "沉降的",
  "subsiding": "沉降",
  "tolerate": "耐受",
  "tolerates": "耐受",
  "tolerated": "被耐受的",
  "tolerating": "耐受",
  "trigger": "触发；引发",
  "triggers": "触发",
  "triggered": "被触发的",
  "triggering": "触发",
  "undergo": "经历；遭受",
  "undergoes": "经历",
  "underwent": "经历的",
  "undergone": "已发生的",
  "uptake": "摄取；吸收",
  "uptakes": "摄取",
  "uptake_field": "摄取",
  "varies": "变化",
  "varied": "变化的",
  "varying": "变化的",
  "yields": "产生",
  "yielded": "产生的",
  "yielding": "产生",
  "adjacent": "邻近的",
  "adequate": "足够的",
  "apparent": "明显的",
  "comparable": "可比的",
  "comprehensive": "综合的；全面的",
  "consistent": "一致的；恒定的",
  "conventional": "常规的",
  "crucial": "关键的",
  "distinct": "明显的；不同的",
  "dominant": "主导的",
  "efficient": "高效的",
  "equivalent": "等价的；相当的",
  "favorable": "有利的",
  "frequent": "频繁的",
  "fundamental": "基本的",
  "gradual": "逐渐的",
  "identical": "相同的",
  "immediate": "立即的",
  "independent": "独立的",
  "inevitable": "不可避免的",
  "inherent": "固有的",
  "innovative": "创新的",
  "intense": "强烈的",
  "intermediate": "中间的",
  "internal": "内部的",
  "minimal": "最小的",
  "mutual": "相互的",
  "nearby": "附近的",
  "numerous": "众多的",
  "obvious": "明显的",
  "optimal": "最佳的",
  "parallel": "平行的",
  "permanent": "永久的",
  "powerful": "强大的",
  "predominant": "主要的",
  "principal": "主要的",
  "random": "随机的",
  "rapid": "快速的",
  "reasonable": "合理的",
  "relevant": "相关的",
  "reliable": "可靠的",
  "representative": "代表性的",
  "respective": "各自的",
  "severe": "严重的",
  "simultaneous": "同时的",
  "sole": "唯一的",
  "strategic": "策略的",
  "subsequent": "随后的",
  "substantial": "大量的",
  "superior": "优越的",
  "theoretical": "理论的",
  "ultimate": "最终的",
  "valid": "有效的",
  "vast": "广阔的",
  "visible": "可见的"
};
;
