/* ============================================================
   推免助手 PushMian Buddy — 种子数据（计算机科学与技术方向）
   说明：仅在首次初始化时写入 localStorage，之后以本地存储为准。
   ============================================================ */

const SEED_VOCAB = [
{term:"时间复杂度",en:"time complexity",def:"衡量算法运行时间随输入规模增长的阶数，常用大 O 记号表示，如 O(n)、O(n log n)。",ex:"Quicksort runs in O(n log n) on average.",syn:"渐进复杂度"},
{term:"空间复杂度",en:"space complexity",def:"算法执行过程中所需的额外存储空间随输入规模增长的阶数。",ex:"Iterative merge sort uses O(n) extra space.",syn:""},
{term:"递归",en:"recursion",def:"函数直接或间接调用自身来求解问题的方法，常配合递推关系与终止条件。",ex:"Recursion can be converted to iteration with an explicit stack.",syn:""},
{term:"分治",en:"divide and conquer",def:"将大问题分解为相互独立的子问题，分别求解后合并结果的算法设计范式。",ex:"Merge sort is a classic divide-and-conquer algorithm.",syn:"分治法"},
{term:"动态规划",en:"dynamic programming",def:"把重叠子问题分解存储并复用结果，避免重复计算的优化方法，通常需要最优子结构。",ex:"Dynamic programming solves the knapsack problem efficiently.",syn:"DP"},
{term:"贪心算法",en:"greedy algorithm",def:"每一步都做当前看起来最优的选择，从而期望达到全局最优的算法设计策略。",ex:"Dijkstra's algorithm is a greedy algorithm.",syn:"贪心法"},
{term:"回溯",en:"backtracking",def:"在解空间中深度优先搜索，遇冲突即回退再试探的穷举式搜索方法。",ex:"N-Queens is typically solved by backtracking.",syn:"回溯搜索"},
{term:"哈希表",en:"hash table",def:"通过哈希函数将键映射到桶位置、平均 O(1) 时间完成增删查的数据结构。",ex:"Hash tables provide average O(1) lookups.",syn:"散列表"},
{term:"哈希冲突",en:"hash collision",def:"多个不同键经哈希函数映射到同一桶的现象，常用链地址法或开放定址法解决。",ex:"Chaining resolves hash collisions with linked lists.",syn:"冲突"},
{term:"链表",en:"linked list",def:"由节点依次通过指针连接的线性结构，插入删除高效但随机访问需 O(n)。",ex:"Linked lists allow O(1) insertion at a known node.",syn:""},
{term:"栈",en:"stack",def:"后进先出（LIFO）的线性结构，主要操作有压栈与弹栈。",ex:"Stacks are used to match parentheses.",syn:"堆栈"},
{term:"队列",en:"queue",def:"先进先出（FIFO）的线性结构，主要操作有入队与出队。",ex:"Queues implement breadth-first search.",syn:""},
{term:"二叉树",en:"binary tree",def:"每个节点最多有两个孩子的树结构，是二叉搜索树与堆的基础。",ex:"A binary tree has at most two children per node.",syn:""},
{term:"二叉搜索树",en:"binary search tree",def:"满足左小右大性质、支持对数级查找的二叉树，但可能退化为链表。",ex:"A balanced BST guarantees O(log n) search.",syn:"BST"},
{term:"红黑树",en:"red-black tree",def:"一种自平衡二叉搜索树，通过颜色约束保证树高近似平衡，插入删除后仍为 O(log n)。",ex:"The Linux kernel uses red-black trees for timers.",syn:""},
{term:"B+树",en:"B+ tree",def:"多路平衡搜索树，数据只存于叶子节点并以链表相连，是数据库与文件系统索引的主流结构。",ex:"MySQL InnoDB uses B+ trees for indexes.",syn:""},
{term:"堆",en:"heap",def:"满足堆性质的完全二叉树，用于实现优先队列与堆排序。",ex:"Heaps implement priority queues.",syn:"二叉堆"},
{term:"排序算法",en:"sorting algorithm",def:"将序列按关键字有序排列的算法，常见有冒泡、选择、插入、归并、快排、堆排等。",ex:"Comparison sorts have a lower bound of O(n log n).",syn:""},
{term:"快速排序",en:"quicksort",def:"基于分治与枢轴划分的排序算法，平均 O(n log n)，最坏 O(n²)。",ex:"Quicksort is usually fastest in practice.",syn:"快排"},
{term:"归并排序",en:"merge sort",def:"分治排序算法，稳定且始终 O(n log n)，但需 O(n) 额外空间。",ex:"Merge sort is stable but not in-place.",syn:"归并"},
{term:"图遍历",en:"graph traversal",def:"按某种顺序访问图全部顶点的过程，主要指深度优先（DFS）与广度优先（BFS）。",ex:"BFS finds shortest paths in unweighted graphs.",syn:"遍历"},
{term:"最短路径",en:"shortest path",def:"在加权图中求两点间权值和最小的路径，典型算法有 Dijkstra 与 Floyd。",ex:"Dijkstra's algorithm requires non-negative edge weights.",syn:""},
{term:"最小生成树",en:"minimum spanning tree",def:"连接图中全部顶点且总权值最小的树，典型算法有 Kruskal 与 Prim。",ex:"Kruskal uses a union-find structure.",syn:"MST"},
{term:"进程",en:"process",def:"正在运行中的程序实例，是资源分配的基本单位，拥有独立地址空间。",ex:"Each process has its own virtual address space.",syn:"过程"},
{term:"线程",en:"thread",def:"进程内的执行流，是 CPU 调度的基本单位，同一进程的线程共享地址空间。",ex:"Threads within a process share memory.",syn:""},
{term:"并发",en:"concurrency",def:"多个任务在同一时间间隔内交替执行，可通过多线程或多进程实现。",ex:"Concurrency improves utilization on multicore CPUs.",syn:"并行"},
{term:"死锁",en:"deadlock",def:"多个进程互相等待对方占有的资源而永远无法继续的僵局状态，需满足互斥、持有并等待、不可剥夺、环路等待四个条件。",ex:"Deadlock can be prevented by resource ordering.",syn:""},
{term:"信号量",en:"semaphore",def:"由计数与 P/V（wait/signal）操作构成、用于进程同步与互斥的经典机制。",ex:"Semaphores solve the producer-consumer problem.",syn:""},
{term:"互斥锁",en:"mutex",def:"保证任意时刻只有一个线程进入临界区的同步原语。",ex:"A mutex protects shared counters from races.",syn:"互斥量"},
{term:"临界区",en:"critical section",def:"访问共享资源的代码段，需互斥进入以保护数据一致性。",ex:"Only one thread may execute a critical section at a time.",syn:""},
{term:"竞态条件",en:"race condition",def:"多个执行流访问共享数据且最终结果依赖于执行次序的不可控现象。",ex:"Race conditions cause nondeterministic output.",syn:"竞争条件"},
{term:"虚拟内存",en:"virtual memory",def:"以分页/分段将逻辑地址与物理地址分离，使程序可使用大于物理内存的地址空间。",ex:"Virtual memory enables memory overcommitment.",syn:""},
{term:"分页",en:"paging",def:"将内存划分为固定大小页框、逻辑空间按页映射的存储管理方式。",ex:"Paging eliminates external fragmentation.",syn:"页面"},
{term:"页置换",en:"page replacement",def:"缺页时选择淘汰哪一页的算法，常见有 FIFO、LRU、Clock 等。",ex:"LRU replacement evicts the least recently used page.",syn:"换页"},
{term:"中断",en:"interrupt",def:"硬件或软件向 CPU 发出的异步事件信号，用于抢占当前执行流转去处理。",ex:"Interrupts drive context switching and I/O.",syn:""},
{term:"系统调用",en:"system call",def:"用户程序请求操作系统内核服务的受控接口，如 read、fork、exec。",ex:"System calls are the gateway between user and kernel mode.",syn:"系统调用"},
{term:"内核态",en:"kernel mode",def:"CPU 执行操作系统内核代码、可访问全部资源与特权指令的运行状态。",ex:"Kernel mode runs privileged instructions.",syn:"管态"},
{term:"用户态",en:"user mode",def:"应用程序受限运行、不能直接访问硬件的 CPU 状态。",ex:"User mode traps into kernel for system calls.",syn:"目态"},
{term:"上下文切换",en:"context switch",def:"CPU 保存当前进程上下文并恢复另一个进程上下文、实现任务切换的过程。",ex:"Excessive context switching degrades throughput.",syn:""},
{term:"缓存",en:"cache",def:"位于主存与 CPU 之间的高速小容量存储，利用局部性原理降低平均访存延迟。",ex:"Cache hits dramatically speed up memory access.",syn:"高速缓存"},
{term:"TCP",en:"transmission control protocol",def:"面向连接、可靠、基于字节流的传输层协议，提供确认重传、流量控制与拥塞控制。",ex:"TCP guarantees ordered and reliable delivery.",syn:"传输控制协议"},
{term:"UDP",en:"user datagram protocol",def:"无连接、不可靠但低延迟的传输层协议，适合实时音视频等场景。",ex:"UDP trades reliability for low latency.",syn:"用户数据报协议"},
{term:"三次握手",en:"three-way handshake",def:"TCP 建立连接时 SYN/SYN+ACK/ACK 的交互过程，用于同步序号并确认双方收发能力。",ex:"The three-way handshake establishes a TCP connection.",syn:"握手"},
{term:"拥塞控制",en:"congestion control",def:"TCP 通过慢启动、拥塞避免、快速重传与快速恢复动态调整发送速率避免网络拥塞。",ex:"Congestion control adapts to network load.",syn:""},
{term:"滑动窗口",en:"sliding window",def:"发送方与接收方维护的一组连续序号范围，用于流量控制与可靠传输。",ex:"Sliding window limits in-flight packets.",syn:""},
{term:"DNS",en:"domain name system",def:"将域名解析为 IP 地址的分层分布式命名系统。",ex:"DNS resolves hostnames to IP addresses.",syn:"域名系统"},
{term:"HTTP",en:"hypertext transfer protocol",def:"基于请求/响应、默认无状态的 Web 应用层协议。",ex:"HTTP requests carry methods like GET and POST.",syn:""},
{term:"HTTPS",en:"hypertext transfer protocol secure",def:"在 HTTP 之上叠加 TLS 加密与身份认证的安全版本协议。",ex:"HTTPS encrypts traffic between browser and server.",syn:""},
{term:"负载均衡",en:"load balancing",def:"将请求按策略分发到多台后端服务器，以提升吞吐与可用性的技术。",ex:"Load balancers distribute traffic across replicas.",syn:"负载均衡"},
{term:"微服务",en:"microservices",def:"将单体应用拆分为可独立部署、通过轻量通信协作的多个小服务架构。",ex:"Microservices scale independently.",syn:"微服务架构"},
{term:"容器",en:"container",def:"基于操作系统级虚拟化、共享内核、隔离资源与命名空间的轻量运行环境。",ex:"Docker containers share the host kernel.",syn:"容器化"},
{term:"分布式系统",en:"distributed system",def:"由多台独立计算机协作完成任务、对用户呈现为单一系统的体系。",ex:"Distributed systems face partial failure and latency.",syn:"分布式"},
{term:"一致性",en:"consistency",def:"分布式系统中多副本数据在并发操作后保持相同状态的性质，包含强一致与最终一致等。",ex:"Raft provides linearizable consistency.",syn:""},
{term:"事务",en:"transaction",def:"数据库操作的基本执行单元，满足原子性、一致性、隔离性与持久性（ACID）。",ex:"Transactions ensure ACID properties.",syn:""},
{term:"索引",en:"index",def:"数据库为加速查询而建立的辅助数据结构，如 B+ 树索引与哈希索引。",ex:"Indexes speed up range and equality queries.",syn:""},
{term:"编译原理",en:"compiler",def:"研究将高级语言翻译为可执行代码的原理与技术，涵盖词法、语法、语义分析与代码生成。",ex:"A compiler transforms source into machine code.",syn:"编译"},
{term:"语法分析",en:"parsing",def:"按文法规则对词法单元序列构建语法树的过程。",ex:"Parsing builds an abstract syntax tree.",syn:""},
{term:"机器学习",en:"machine learning",def:"让程序从数据中自动学习规律并对新样本进行预测的学科。",ex:"Machine learning generalizes from training data.",syn:"ML"},
{term:"神经网络",en:"neural network",def:"由大量带权连接的神经元分层组成的参数化模型，通过反向传播训练。",ex:"Neural networks approximate complex functions.",syn:""},
{term:"过拟合",en:"overfitting",def:"模型在训练集表现好但在新数据泛化差的现象，常用正则化与交叉验证缓解。",ex:"Regularization reduces overfitting.",syn:"过学习"},
{term:"正则化",en:"regularization",def:"在损失函数中加入惩罚项以约束模型复杂度、抑制过拟合的技术。",ex:"L2 regularization shrinks weights toward zero.",syn:""},
{term:"梯度下降",en:"gradient descent",def:"沿损失函数负梯度方向迭代更新参数以最小化损失的优化算法。",ex:"Stochastic gradient descent scales to big data.",syn:"梯度下降法"}
];

/* —— 词汇表扩充（术语表条目，def 为中文释义） —— */
const SEED_VOCAB_TB = [
  {
    "term": "计算机科学",
    "en": "Computer Science",
    "def": "研究计算理论、算法与软硬件系统的学科。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "数据结构",
    "en": "Data Structure",
    "def": "组织和存储数据的方式，如数组、链表、树、图。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "算法",
    "en": "Algorithm",
    "def": "解决特定问题的一系列明确指令，强调正确性与复杂度。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "操作系统",
    "en": "Operating System",
    "def": "管理计算机硬件与软件资源、为用户提供接口的系统软件。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "计算机网络",
    "en": "Computer Network",
    "def": "将多台计算机互联以实现资源共享与通信的体系。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "计算机体系结构",
    "en": "Computer Architecture",
    "def": "研究指令集、存储层次与处理器组织的学科。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "数据库系统",
    "en": "Database System",
    "def": "管理数据的存储、查询与事务的系统软件。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "软件工程",
    "en": "Software Engineering",
    "def": "以工程化方法开发与维护软件的学科。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "人工智能",
    "en": "Artificial Intelligence",
    "def": "研究如何让计算机模拟人类智能行为的学科。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "编程语言",
    "en": "Programming Language",
    "def": "用于编写程序的规范化形式语言，如 C、Python、Java。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "面向对象",
    "en": "Object-Oriented Programming",
    "def": "以对象与类为核心、强调封装继承多态的编程范式。",
    "ex": "",
    "syn": "OOP",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "汇编语言",
    "en": "Assembly Language",
    "def": "与机器指令一一对应的低级符号语言。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "版本控制",
    "en": "Version Control",
    "def": "记录并管理文件版本演变的工具，如 Git。",
    "ex": "",
    "syn": "VCS",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "测试",
    "en": "Software Testing",
    "def": "通过运行或静态分析验证程序正确性的过程。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "调试",
    "en": "Debugging",
    "def": "定位并修复程序缺陷（bug）的过程。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "内存泄漏",
    "en": "Memory Leak",
    "def": "程序未能释放不再使用的内存导致可用内存持续减少。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "垃圾回收",
    "en": "Garbage Collection",
    "def": "自动回收不再被引用的内存对象的机制。",
    "ex": "",
    "syn": "GC",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "多线程",
    "en": "Multithreading",
    "def": "在单个进程内运行多个执行流的编程模型。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "锁",
    "en": "Lock",
    "def": "用于保证多线程互斥访问共享资源的同步机制。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "进程调度",
    "en": "Process Scheduling",
    "def": "操作系统按某种策略为就绪进程分配 CPU 的过程。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "时间片轮转",
    "en": "Round-Robin",
    "def": "按固定时间片轮流调度进程的算法。",
    "ex": "",
    "syn": "RR",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "优先级调度",
    "en": "Priority Scheduling",
    "def": "按进程优先级高低决定执行顺序的调度算法。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "存储层次",
    "en": "Memory Hierarchy",
    "def": "寄存器、缓存、主存、外存按速度与成本组织的层次结构。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "虚拟地址",
    "en": "Virtual Address",
    "def": "程序视角的地址，经 MMU 翻译为物理地址。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "物理地址",
    "en": "Physical Address",
    "def": "内存实际单元的地址。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "IP地址",
    "en": "IP Address",
    "def": "网络层为主机分配的全局标识地址（IPv4/IPv6）。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "子网掩码",
    "en": "Subnet Mask",
    "def": "用于划分 IP 地址中网络号与主机号的掩码。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "路由器",
    "en": "Router",
    "def": "在网络层转发数据包、连接不同网络的设备。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "交换机",
    "en": "Switch",
    "def": "在数据链路层按 MAC 地址转发帧的设备。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "网关",
    "en": "Gateway",
    "def": "连接异构网络的转发/协议转换节点。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "防火墙",
    "en": "Firewall",
    "def": "按安全策略过滤网络流量的安全设备。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "加密",
    "en": "Encryption",
    "def": "将明文转换为密文以保护信息机密性的技术。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "数字签名",
    "en": "Digital Signature",
    "def": "用私钥对消息摘要签名以验证完整性与来源。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "认证",
    "en": "Authentication",
    "def": "验证用户或设备身份真实性的过程。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "SQL",
    "en": "Structured Query Language",
    "def": "用于关系数据库定义与操作数据的一门声明式语言。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "关系模型",
    "en": "Relational Model",
    "def": "以关系（二维表）组织数据的数据库模型。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "主键",
    "en": "Primary Key",
    "def": "唯一标识表中每一行记录的属性或属性组合。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "外键",
    "en": "Foreign Key",
    "def": "引用其他表主键以建立关联的属性。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "范式",
    "en": "Normal Form",
    "def": "规范关系模式设计、减少冗余与异常的标准（1NF~BCNF 等）。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "串行化",
    "en": "Serializability",
    "def": "并发事务执行结果等价于某串行执行的性质。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "两阶段锁",
    "en": "Two-Phase Locking",
    "def": "保证事务可串行化的加锁协议，分扩展与收缩两阶段。",
    "ex": "",
    "syn": "2PL",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "MapReduce",
    "en": "MapReduce",
    "def": "将大规模数据处理拆为映射与归约两阶段的编程模型。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "云计算",
    "en": "Cloud Computing",
    "def": "通过网络按需提供可伸缩计算与存储资源的模式。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "虚拟化",
    "en": "Virtualization",
    "def": "用软件在物理资源上抽象出多份虚拟资源的技术。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "大模型",
    "en": "Large Language Model",
    "def": "参数量巨大的神经网络语言模型，如 GPT、LLaMA。",
    "ex": "",
    "syn": "LLM",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "迁移学习",
    "en": "Transfer Learning",
    "def": "将已有任务学到的知识迁移到新任务以提高效果。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "卷积神经网络",
    "en": "Convolutional Neural Network",
    "def": "以卷积层提取局部特征的深度学习模型，适用于图像。",
    "ex": "",
    "syn": "CNN",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "循环神经网络",
    "en": "Recurrent Neural Network",
    "def": "带时序反馈结构的神经网络，适合序列数据。",
    "ex": "",
    "syn": "RNN",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "注意力机制",
    "en": "Attention Mechanism",
    "def": "为序列中不同位置分配权重、突出重要信息的机制，是 Transformer 核心。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "Transformer",
    "en": "Transformer",
    "def": "基于自注意力与位置编码的深度学习架构，大模型的基础。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "反向传播",
    "en": "Backpropagation",
    "def": "按链式法则从输出层逐层反传梯度、更新网络参数的算法。",
    "ex": "",
    "syn": "BP",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "准确率",
    "en": "Accuracy",
    "def": "预测正确的样本占总样本的比例，是分类任务常用指标。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "精确率",
    "en": "Precision",
    "def": "预测为正类中真正例的比例。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "召回率",
    "en": "Recall",
    "def": "真正例中被正确预测出的比例。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "F1分数",
    "en": "F1 Score",
    "def": "精确率与召回率的调和平均，用于综合衡量分类性能。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  },
  {
    "term": "交叉验证",
    "en": "Cross-Validation",
    "def": "将数据集切分多次训练与验证，以稳定评估模型的方法。",
    "ex": "",
    "syn": "",
    "status": "未标记",
    "nextReview": ""
  }
]
;

const CHINESE_GLOSSARY = {
  "algorithm": "算法",
  "data structure": "数据结构",
  "time complexity": "时间复杂度",
  "space complexity": "空间复杂度",
  "recursion": "递归",
  "iteration": "迭代",
  "divide and conquer": "分治法",
  "dynamic programming": "动态规划",
  "greedy": "贪心",
  "backtracking": "回溯",
  "brute force": "暴力解法",
  "hash table": "哈希表",
  "hash function": "哈希函数",
  "collision": "冲突",
  "linked list": "链表",
  "stack": "栈",
  "queue": "队列",
  "array": "数组",
  "tree": "树",
  "binary tree": "二叉树",
  "binary search tree": "二叉搜索树",
  "balanced tree": "平衡树",
  "red-black tree": "红黑树",
  "b+ tree": "B+树",
  "heap": "堆",
  "priority queue": "优先队列",
  "graph": "图",
  "vertex": "顶点",
  "edge": "边",
  "traversal": "遍历",
  "depth-first search": "深度优先搜索",
  "breadth-first search": "广度优先搜索",
  "shortest path": "最短路径",
  "minimum spanning tree": "最小生成树",
  "sorting": "排序",
  "stable": "稳定的",
  "in-place": "原地",
  "pivot": "枢轴",
  "binary search": "二分查找",
  "complexity": "复杂度",
  "bound": "界",
  "process": "进程",
  "thread": "线程",
  "concurrency": "并发",
  "parallelism": "并行",
  "synchronization": "同步",
  "mutex": "互斥锁",
  "semaphore": "信号量",
  "deadlock": "死锁",
  "starvation": "饥饿",
  "race condition": "竞态条件",
  "critical section": "临界区",
  "scheduler": "调度器",
  "time slice": "时间片",
  "context switch": "上下文切换",
  "virtual memory": "虚拟内存",
  "paging": "分页",
  "segmentation": "分段",
  "page fault": "缺页",
  "page replacement": "页置换",
  "cache": "缓存",
  "locality": "局部性",
  "interrupt": "中断",
  "system call": "系统调用",
  "kernel": "内核",
  "user mode": "用户态",
  "kernel mode": "内核态",
  "instruction": "指令",
  "pipeline": "流水线",
  "cpu": "中央处理器",
  "memory": "内存",
  "disk": "磁盘",
  "protocol": "协议",
  "tcp": "TCP",
  "udp": "UDP",
  "handshake": "握手",
  "congestion": "拥塞",
  "window": "窗口",
  "routing": "路由",
  "subnet": "子网",
  "packet": "数据包",
  "frame": "帧",
  "switch": "交换机",
  "router": "路由器",
  "gateway": "网关",
  "firewall": "防火墙",
  "domain name": "域名",
  "dns": "DNS",
  "http": "HTTP",
  "https": "HTTPS",
  "encryption": "加密",
  "decryption": "解密",
  "signature": "签名",
  "authentication": "认证",
  "database": "数据库",
  "relation": "关系",
  "schema": "模式",
  "query": "查询",
  "index": "索引",
  "transaction": "事务",
  "atomic": "原子的",
  "consistency": "一致性",
  "isolation": "隔离性",
  "durability": "持久性",
  "locking": "加锁",
  "optimistic": "乐观的",
  "distributed": "分布式",
  "replica": "副本",
  "consensus": "共识",
  "sharding": "分片",
  "microservice": "微服务",
  "container": "容器",
  "virtualization": "虚拟化",
  "cloud": "云",
  "compiler": "编译器",
  "token": "词法单元",
  "parsing": "语法分析",
  "abstract syntax tree": "抽象语法树",
  "lexical analysis": "词法分析",
  "semantic analysis": "语义分析",
  "code generation": "代码生成",
  "optimization": "优化",
  "interpreter": "解释器",
  "virtual machine": "虚拟机",
  "machine learning": "机器学习",
  "deep learning": "深度学习",
  "neural network": "神经网络",
  "neuron": "神经元",
  "weight": "权重",
  "bias": "偏置",
  "activation": "激活",
  "loss function": "损失函数",
  "gradient": "梯度",
  "gradient descent": "梯度下降",
  "overfitting": "过拟合",
  "underfitting": "欠拟合",
  "regularization": "正则化",
  "training set": "训练集",
  "validation set": "验证集",
  "test set": "测试集",
  "feature": "特征",
  "label": "标签",
  "supervised": "有监督的",
  "unsupervised": "无监督的",
  "reinforcement": "强化",
  "classification": "分类",
  "regression": "回归",
  "clustering": "聚类",
  "accuracy": "准确率",
  "precision": "精确率",
  "recall": "召回率",
  "epoch": "轮次",
  "batch": "批次",
  "attention": "注意力",
  "tokenizer": "分词器",
  "embedding": "嵌入向量",
  "open source": "开源",
  "version control": "版本控制",
  "repository": "仓库",
  "branch": "分支",
  "commit": "提交",
  "merge": "合并",
  "pull request": "拉取请求",
  "bug": "缺陷",
  "debug": "调试",
  "test case": "测试用例",
  "unit test": "单元测试",
  "integration test": "集成测试",
  "continuous integration": "持续集成",
  "deployment": "部署",
  "monitor": "监控",
  "latency": "延迟",
  "throughput": "吞吐量",
  "reliability": "可靠性",
  "availability": "可用性",
  "scalability": "可扩展性",
  "security": "安全性",
  "privacy": "隐私",
  "interface": "接口",
  "dependency": "依赖",
  "framework": "框架",
  "library": "库",
  "software": "软件",
  "hardware": "硬件",
  "system": "系统",
  "network": "网络",
  "server": "服务器",
  "client": "客户端",
  "backend": "后端",
  "frontend": "前端",
  "database engine": "数据库引擎",
  "open source community": "开源社区",
  "significant": "显著的",
  "efficient": "高效的",
  "robust": "鲁棒的",
  "reliable": "可靠的",
  "scalable": "可扩展的",
  "accurate": "准确的",
  "comprehensive": "全面的",
  "valid": "有效的",
  "sufficient": "充足的",
  "optimal": "最优的",
  "approximate": "近似的",
  "greedy strategy": "贪心策略",
  "heuristic": "启发式",
  "trade-off": "权衡"
};
